### ISSUE TITLE
Feature request: pasting an image

### ISSUE THREAD

**Issue by Flimm** [TenderOwl/Frog#120] opened 2023-07-13 20:06 UTC
I would like to be able to copy image data straight into Frog without having to save it as a file first.

Here are ways of copying image data:

- In Firefox and in Chrome, I can right-click on an image and choose "Copy Image"
- In GIMP, I can select part of an image, and copy it
- In certain messaging apps, I can copy an image that is sent to me.
- In GNOME, I can press <kbd>PrintScreen</kbd> to launch GNOME's built-in screenshot functionality. Once I've taken a screenshot, the image is copied to the clipboard (in addition to being saved as a file). A notification says "You can paste the image from the clipboard"

It would be great if I could press <kbd>control</kbd>-<kbd>v</kbd> to paste it into Frog.

**Comment by amka** [comment] 2023-07-17 08:32
Duplicate of #74, #118.
Will be available in the next release.

**Closed** 2023-07-17 08:33 UTC
Labels: duplicate
